version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GIT_SHA: ${GIT_SHA:-unknown}
    image: ${CHATWOOT_IMAGE:-lakchelink:latest}
    env_file: .env ## Change this file for customized env variables
    volumes:
      - storage_data:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    env_file: .env
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-lakchelink_production}
      - POSTGRES_USER=${POSTGRES_USERNAME:-lakchelink}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'

  adminer:
    image: adminer:4
    restart: always
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    volumes:
      - ./docker/adminer/adminer.css:/var/www/html/adminer.css:ro
      - ./public/brand-assets/lakche-logo.png:/var/www/html/lakche-logo.png:ro
    ports:
      - '127.0.0.1:8081:8080'

volumes:
  storage_data:
  postgres_data:
  redis_data:
